### ISSUE TITLE
Combined efforts

### ISSUE THREAD

**Issue by dvzrv** [tartina/a2jmidid#1]
Hi @tartina!

I maintain a2jmidid for Arch Linux (amongst other things). As the original maintainer of the software (Nedko) is MIA, I started to port a2jmidid to python3 as well:
https://github.com/linuxaudio/a2jmidid

It would be awesome, if we could combine our efforts there. I would like to be able to do a new release of the software soon, to drop python2.

Please note, that [I have chosen a more radical rewrite of a2j_control](https://github.com/linuxaudio/a2jmidid/commit/a58bcea3e0815138bf6f4de97a9763346403d73f) to drop dependencies and be more in line with a common pythonic workflow.

Furthermore I would like to switch to meson as build system, to be able to drop in tree dependencies (i.e. waf), that are super brittle to use (from a packaging perspective).

Please let me know, if you would be up for being part of the maintenance team for a2jmidid in the linuxaudio organization.

**Comment by tartina** [comment]
Il giorno ven 20 set 2019 alle ore 19:53 David Runge
<notifications@github.com> ha scritto:
>
> Hi @tartina!
>
> I maintain a2jmidid for Arch Linux (amongst other things). As the original maintainer of the software (Nedko) is MIA, I started to port a2jmidid to python3 as well:
> https://github.com/linuxaudio/a2jmidid
>
> It would be awesome, if we could combine our efforts there. I would like to be able to do a new release of the software soon, to drop python2.

Yes, of course I agree with you.
>
> Please note, that I have chosen a more radical rewrite of a2j_control to drop dependencies and be more in line with a common pythonic workflow.

Great work, I'm not a great pythonist
>
> Furthermore I would like to switch to meson as build system, to be able to drop in tree dependencies (i.e. waf), that are super brittle to use (from a packaging perspective).

Unfortunately I don't know meson, I can manage autotools, and a little
bit of maven, gradle and waf.
>
> Please let me know, if you would be up for being part of the maintenance team for a2jmidid in the linuxaudio organization.

Yes, of course, my plan is to release a new python3 version of the
program to be safe against Fedora's python2 deadline (which should be
on November 2019), then merge our work into one.

Thanks a lot for you work.
Ciao
Guido

**Comment by dvzrv** [comment]
On 2019-09-23 02:34:17 (-0700), Guido wrote:
> Unfortunately I don't know meson, I can manage autotools, and a little
> bit of maven, gradle and waf.

I think you will like meson then. I've merged my changes:

https://github.com/linuxaudio/a2jmidid

I will update the README and installation information (hopefully today).
A release can be made shortly after.

It would be fabulous, if you could open pull requests for the other
changes (e.g. architecture fixes).

> > Please let me know, if you would be up for being part of the
> > maintenance team for a2jmidid in the linuxaudio organization.
> 
> Yes, of course, my plan is to release a new python3 version of the
> program to be safe against Fedora's python2 deadline (which should be
> on November 2019), then merge our work into one.

Oh, Fedora is also going to implement a hard drop? :)
Well, similar will happen for Arch Linux actually.

I'm currently also trying to be able to still build Ardour. It's python2
waf unfortunately. with *lots* of custom scriptery... :-/

Best,
David

-- 
https://sleepmap.de

**Comment by dvzrv** [comment]
@tartina I've invited you to the repo.
I've also released a new version. Feel free to test :)
Closing this now. Thanks!
